apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kortex.fullname" . }}-web
  labels:
    {{- include "kortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "kortex.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "kortex.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: web
          image: {{ include "kortex.image" (dict "Values" .Values "repo" .Values.image.web.repository "tag" .Values.image.web.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kortex.fullname" . }}-web
  labels:
    {{- include "kortex.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kortex.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
